idx: 1
op_list:
- data:
  - '867'
  - '1436'
  op_type: move
- data:
  - '868'
  - '1376'
  op_type: move
- data:
  - '868'
  - '1375'
  op_type: move
- data:
  - '868'
  - '1347'
  op_type: move
- data:
  - '864'
  - '1250'
  op_type: move
- data:
  - '863'
  - '1191'
  op_type: move
- data:
  - '863'
  - '1153'
  op_type: move
tp_area_id: production_area_building_east_side
tp_name: 物流通道
